inherit:
  - models/standard.yaml
  - wandb.yaml

model:
  n_dims: 20        # input dimension
  n_positions: 20   # ensure 2 * n_positions >= T = 2 * 8 + 1 = 17, so 20 is enough

training:
  task: group_mixture_linear
  data: group_mixture_linear
  task_kwargs:
    n_components: 2            # K (reduced from 3 to make easier)
    contexts_per_component: 8  # C (increased to 8 for more signal per component)
    noise_std: 0.0
    scale: 0.5  # Reduced scale to make values smaller, easier to learn
  batch_size: 64
  learning_rate: 0.0005  # Increased from 0.0001 for faster learning
  save_every_steps: 1000
  keep_every_steps: 100000
  train_steps: 5001
  curriculum:
    dims:
      start: 20
      end: 20
      inc: 1
      interval: 2000
    points:
      start: 17   # T = K * C + 1 = 2 * 8 + 1 = 17
      end: 17
      inc: 2
      interval: 2000

out_dir: ../models/group_mixture_linear

wandb:
  name: "group_mixture_linear"

test_run: False

