inherit:
  - models/standard.yaml
  - wandb.yaml

model:
  n_dims: 20        # input dimension
  n_positions: 30   # ensure 2 * n_positions >= T = K * C + 1

training:
  task: group_mixture_linear
  data: group_mixture_linear
  task_kwargs:
    n_components: 3            # K
    contexts_per_component: 4  # C
    noise_std: 0.0
    scale: 1.0
  batch_size: 64
  learning_rate: 0.0001
  save_every_steps: 1000
  keep_every_steps: 100000
  train_steps: 5001
  curriculum:
    dims:
      start: 20
      end: 20
      inc: 1
      interval: 2000
    points:
      start: 13   # T = K * C + 1 = 3 * 4 + 1
      end: 13
      inc: 2
      interval: 2000

out_dir: ../models/group_mixture_linear

wandb:
  name: "group_mixture_linear"

test_run: False

