inherit:
  - models/standard.yaml
  - wandb.yaml

model:
  n_dims: 5
  n_positions: 30 

training:
  task: group_mixture_linear
  data: group_mixture_linear
  task_kwargs:
    n_components: 1 
    contexts_per_component: 10
    target_cluster_context_points: 3
    noise_std: 0.0
    scale: 0.1 
  batch_size: 64
  learning_rate: 0.0005
  train_steps: 2001
  
  curriculum:
    dims:
      start: 5
      end: 5
      inc: 1
      interval: 2000
    points:
      start: 14  
      end: 14
      inc: 2
      interval: 2000

out_dir: ../models/test_fixed
test_run: False